### ISSUE TITLE
Correction to front--page.twig

### ISSUE THREAD

**Issue by tmddev** [norwegianblue-nz/keplerchallenge2#1]
I found a mistake in page—front.twig line 108:
<div id="preface-first-layout" class=" {{ region_classes.preface }}preface-first-layout inner-wrapper clearfix">
Needs a space after “{{ region_classes.preface }}” - currently rendering as “with--preface-fourthpreface-first-layout” as opposed to “with--preface-fourth preface-first-layout”

**Comment by norwegianblue-nz** [comment]
Fixed
