### ISSUE TITLE
Non-SAML User logout

### ISSUE THREAD

**Issue by tmddev** [norwegianblue-nz/keplerchallenge2#11]
Roo to see if it’s possible to auto log-out any non-admin user who has used entries/user (as opposed to the correct SAML login route from BROD). 

**NOTE** - must not cause issue for one-time logins using password reset though.

**Comment by tmddev** [comment]
Roo has created "/node/266" for account login-error.
Checking issue related to direct logout (/user/logout) on ENTRIES - goes to same landing page and doesn't log out on BROD. This is an issue since user will **THINK** they are still logged in to entries since BROD displays logged in.

**Comment by norwegianblue-nz** [comment]
> Roo has created "/node/266" for account login-error.
This was achieved by redirects.

Auto-logout is simple. A rule has been created on the entries system to redirect to logout if the login path has no appended redirect (a login from D7 won't, but a login from D8 will have SAML stuff appended to the URL) and if the user is not an admin.

A redirect was also created on logout to go to node/266. However, could not get this rule to fire only if logout was directly from the D7 entries system, so even valid logout attempts were redirected to the error page. 
Logout redirect disabled.

**Comment by norwegianblue-nz** [comment]
UPDATE
reworked the rules.
The D7 login rule now has an addtional action - php code to log them out. 
This rule only fires if loggin in directly on the D7 site.
Also has additional condition to ensure that it doesn't fire for one-time-login links
The D7 rule to logout is not required

Ad additional rule is in place to logout and redirect when a user updates the profile (changes password etc.) So after a password reset, user logs in with one-time-login link, resets password, and is logged out and redirected to a suitably worded page on the D8 site
