### ISSUE TITLE
"You are not authorized" message

### ISSUE THREAD

**Issue by tmddev** [norwegianblue-nz/keplerchallenge2#13]
Potentially change message that states "Access denied - You are not authorized to access this page." to reflect necessity to login (inc direction to main site for SAML). This is confusing for some users who expect that they *should* have access and not sure why.

*Possibly done as a patch so not a re-write of core during each update.

**Comment by norwegianblue-nz** [comment]
Created a new page at /node/272 and configured Drupal to use this page for all 403 errors

_NOTE: The config on Scud points to node/243 as I don't have 272 nodes on Scud. Will need to reconfigure Brod after git pull._
