### ISSUE TITLE
Hide login on validated email page

### ISSUE THREAD

**Issue by tmddev** [norwegianblue-nz/keplerchallenge2#14]
Poss use CSS to hide login and text on landing page from validation of account email. Should be able to target using status message.

Roo to investigate possibilities of login-toboggan and "first login" redirect first.

**Note**: this may be mitigated by other issue "log-out non-admin user".

**Comment by tmddev** [comment]
> Note: this may be mitigated by other issue "log-out non-admin user".
This wouldn't work - would still need CSS.  in that instance.
Loggin Toboggan has no default settings available - Roo to investigate possibility of using a rule.

**Comment by norwegianblue-nz** [comment]
> Roo to investigate possibility of using a rule.
Not possible as the URL is the same as the one for password reset.
Will have to do with css only.

**Comment by norwegianblue-nz** [comment]
Another option would be to let them (indeed encourage) login at this point (ie when they have just validated) and then as this is first login, a rule can be used to redirect them to the profile_updated page  (or similar) and log them out

**Comment by tmddev** [comment]
THINK this will be OK - Just need to think of a way to make it MEANT to happen ;) More BS to invent! LOL

**Comment by norwegianblue-nz** [comment]
It did get added eventually to the issue. 

Just took a while.

Andrew Pealing
+64 27 482 1599
https://norwegian.blue
