### ISSUE TITLE
Redirect arrival at ENTRIES when logged in.

### ISSUE THREAD

**Issue by tmddev** [norwegianblue-nz/keplerchallenge2#17]
Re-direct users from entries.keplerchallenge.co.nz to keplerchallenge.co.nz/index after 10secs if already logged in with SAML. This is to stop/reduce unwanted use of ENTRIES site.

**Comment by norwegianblue-nz** [comment]
Have I missed something here?
Won't this cause issues when users legitimately need to use the entres site for updating profile or actually entering ?

**Comment by tmddev** [comment]
Tim to update existing Entries front - poss with logged-in and logged-out targeted message to the effect that it's not a page for general use. 
Before fulfilling, test changes to SAML and redirects.

**Comment by tmddev** [comment]
Done
