### ISSUE TITLE
Check account email messages to users

### ISSUE THREAD

**Issue by tmddev** [norwegianblue-nz/keplerchallenge2#19]
Check content of emails to users relating to account creation.
Check all links are as required.
Ideally also style messages using html. Currently rich text(?) (or choice to receive plain) but un-styled.

**Comment by norwegianblue-nz** [comment]
Also applies to emails sent by Store.
Roo to investigate HTML mail options - perhaps Swift as an option

**Comment by norwegianblue-nz** [comment]
email sent when account is created has been updated.
Account creation links work.
HTML emails now sent from (new) store. Require some styling
Closing this issue and opening #63 just regarding the Store emails.
