### ISSUE TITLE
Remove link from partner logo to it's node

### ISSUE THREAD

**Issue by tmddev** [norwegianblue-nz/keplerchallenge2#20]
Logos on home page currently link to the node that generated them. This needs turning off (or if possible) redirecting to the URL of the partner(?)) **or** directing to /our-partners page...

This is also the case on the /our-partners page which means the nodes can be accessed (which is outside of scope and not wanted).

**Comment by norwegianblue-nz** [comment]
Removed from the logo.
Left on the 'title' at Tim's suggestion
