### ISSUE TITLE
Gallery image group titles

### ISSUE THREAD

**Issue by tmddev** [norwegianblue-nz/keplerchallenge2#23]
Tim to discuss with Viv if we need the image group title displayed and also that they would not be editable.

**Comment by tmddev** [comment]
Viv wants titles for each group of pics as follows:

1. Starting the Kepler Challenge
2. Making it through the bush to Luxmore Hut
3. Running across the alpine section
4. Making the long descent into the Iris Burn Valley
5. On the home straight.
6. Finished at last!

Didn't discuss the non-editablility of these but decided we'll do that if requested later.

**Comment by norwegianblue-nz** [comment]
Taxonomy terms added with display order in the order above
