### ISSUE TITLE
Contact us form

### ISSUE THREAD

**Issue by tmddev** [norwegianblue-nz/keplerchallenge2#25]
Contact us page form

**Comment by norwegianblue-nz** [comment]
Does this refer to a std contact us page with form-to-email or a "block" to insert in various places ?

**Comment by tmddev** [comment]
May depend on ability for editors to change text.

Essentially just one page with simple form. POTENTIALLY might have target of contact? (Eg race sec, media, and committee) but needs clarification with Viv/Kepler.

Most likely simple form on a page and not block.

**Comment by norwegianblue-nz** [comment]
Do they need to store these messages in the database or is it enough to simply get an email?

**Comment by tmddev** [comment]
I think just the email will be fine - IF it needs anything different it can be a later enhancement.

Form now added and styled... May required edits from Committee.
