### ISSUE TITLE
Cart design and CSS

### ISSUE THREAD

**Issue by tmddev** [norwegianblue-nz/keplerchallenge2#30]
Tim and Roo to look at options other than table for cart page, and decide on layout /design/elements required.

Bug?: Odd extra "Price NZ$35.00" - not sure where it's coming from.
html inc. .views-field-purchased-entity - maybe a view setting?

**Comment by norwegianblue-nz** [comment]
What's displayed and the label's thereof is simple. It's controlled by a view
I've edited the view on Scud to alter the labels etc.
There are several options for how it's displayed.:
    Grid
    HTML List (numbered or un-numbered)
    Table
    Unformatted list
Although tables are a pain in responsive design. this is actually appropriate. It's tabular data.
Only table gives you the label once at the top of a column.
The others all give inline label for each lineitem
I've left Scud in "Grid" to give an indication of what that gives.

**Comment by tmddev** [comment]
H1 title for page. (Cart and through checkout)
Remove 'Remove'
See if GST is easy to add BUT leave off for now
Include line 'item' description

Cart: Remove 'Example'?
bug - cart details removed on 'back' from 'continue to review' page

**Comment by tmddev** [comment]
GST is all that's left here. Closed and opened as different issue.
