### ISSUE TITLE
Re-set 404 and 403 pages

### ISSUE THREAD

**Issue by tmddev** [norwegianblue-nz/keplerchallenge2#31]
These were created but re-directs have been lost in conifg push - Need re-instating on SCUD
404 = /404-not-found
403 = /notallowed

Note - is the crashing car copyright free? :) If not I need to find another image. 
Poss Martin Dent. (no that pun was NOT intended)

**Comment by norwegianblue-nz** [comment]
> These were created but re-directs have been lost in conifg push - Need re-instating on SCUD

Done

> is the crashing car copyright free?

Don't know. Can't find it on the internet.
Perhaps a picture of a runner stumbling ? We could set something up ?

**Comment by tmddev** [comment]
Done, closing - adding new issue for image on 403.
