### ISSUE TITLE
Display username when logged in.

### ISSUE THREAD

**Issue by norwegianblue-nz** [norwegianblue-nz/keplerchallenge2#34]
This can be acheived very simply using tokens.
I've edited the logged-in block on Scud to demonstrate. Had to edit the css to get it to display (else hidden by the stripe).
Here's a screenshot with the stripe set to not have a  bg image
![screenshot_20180413_215050](https://user-images.githubusercontent.com/2801479/38728804-070cf5cc-3f65-11e8-8f1a-56d08ed7d54c.png)

**Comment by tmddev** [comment]
Reconfigured and styled.
