### ISSUE TITLE
Check permissions on FAQ page for editor access

### ISSUE THREAD

**Issue by tmddev** [norwegianblue-nz/keplerchallenge2#40]

**Comment by norwegianblue-nz** [comment]
It's "General Content" so it will get same permissions as all "General Content" 
website_editor can create, and edit any node of this type.
Is this page special in some way that it needs unique permissions ?

**Comment by tmddev** [comment]
That was MY query! LOL

Basically I had to add extra code to the page to make the show/hide work... this meant that I used the FULL HTML text mode which editors can't. ... might simply be able to just do it as BASIC HTML and educate as to editing. Tim to check and report :)

**Comment by tmddev** [comment]
OK - this will work on BASIC format but needs CSS changing to SHOW the answer for editors in CKE. Added to CKE issue.
