### ISSUE TITLE
Redirect/Logout on Profile Update

### ISSUE THREAD

**Issue by norwegianblue-nz** [norwegianblue-nz/keplerchallenge2#42]
This needs a total re-think.
There are two problems with the current process.

1. The logout only logs user out of Entries system.
2. Additionally, the updates to the profile are not saved.

**Comment by tmddev** [comment]
Bother... I thought we had that aspect sussed though...

**Comment by norwegianblue-nz** [comment]
Seems the sensible thing to do is simply redirect, without the logout step.
That way, they are left logged in, which is better from a user point of view, and the edits are saved, but they are not left at the entries site.
Tested on Scud/Tyke Dev environment. _Pass_

**Comment by norwegianblue-nz** [comment]
Implemented above soln on Brod.
Also altered the logo & slogan link to point to https://keplerchallenge.co.nz
