### ISSUE TITLE
Change "Access Denied" message on entries.kep

### ISSUE THREAD

**Issue by tmddev** [norwegianblue-nz/keplerchallenge2#43]
Can't recall if this is possible... there is a link on the main site to:
https://entries.keplerchallenge.co.nz/user/me
("Please make sure that you keep the contact details in your Kepler account up-to-date so that you don’t miss out ...")

If the page's text can't be changed, maybe I should add a "no logged in" block message ala FWF?

**Comment by norwegianblue-nz** [comment]
Create a node on entries system to use as 403 pages, and set this as the 403 page in system config.
NOTE - perhaps a nice 404 page should be created at the same time

**Comment by tmddev** [comment]
Done
